services:
  ssh:
    build:
      context: .
      dockerfile: DockerfileSSH
    ports:
      - "22:22"
  telnet:
    build:
      context: .
      dockerfile: DockerfileTelnet
    ports:
      - "23:23"
  redis:
    build:
      context: .
      dockerfile: DockerfileRedis
    ports:
      - "6379:6379"
